# Generated by Django 4.2 on 2023-04-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roundinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundnumber', models.IntegerField(db_column='roundNumber')),
                ('firstnum', models.IntegerField(db_column='firstNum')),
                ('secondnum', models.IntegerField(db_column='secondNum')),
                ('thirdnum', models.IntegerField(db_column='thirdNum')),
                ('fourthnum', models.IntegerField(db_column='fourthNum')),
                ('fifthnum', models.IntegerField(db_column='fifthNum')),
                ('sixthnum', models.IntegerField(db_column='sixthNum')),
            ],
            options={
                'db_table': 'roundInfo',
                'managed': False,
            },
        ),
    ]
